font_family JetBrainsMono Nerd Font Propo
font_size 15
bold_font_family JetBrainsMono Nerd Font Propo
bold_font_style Bold
italic_font_family JetBrainsMono Nerd Font Propo
italic_font_style Italic
bold_italic_font_family JetBrainsMono Nerd Font Propo
bold_italic_font_style Bold Italic

# Opacidade da janela
background_opacity 0.8

# Definindo o TERM
env TERM=xterm-256color

include ./nord.conf
