## Ajustes para sugestões ZSH visíveis
# Polar night
#nord0 #1a1f28
#nord1 #232834
#nord2 #2d3441
#nord3 #3a4252

# Snow storm
#nord4 #d0d8e5
#nord5 #dde2ec
#nord6 #e6eaf1

# Frost
#nord7 #8ab4b3
#nord8 #83b6c8
#nord9 #7a96b7
#nord10 #5779a2

# Aurora
#nord11 #b85c65
#nord12 #c87f6a
#nord13 #e5c17f
#nord14 #9db583
#nord15 #ae86a3

foreground            #d0d8e5
background            #1a1f28
selection_foreground  #e6eaf1
selection_background  #232834

mark1_foreground #c87f6a
mark2_foreground #8ab4b3
mark3_foreground #9db583

url_color #83b6c8

cursor            #d0d8e5
cursor_text_color #4a5263

active_tab_foreground   #e6eaf1
active_tab_background   #3a4252
inactive_tab_foreground #7d8799
inactive_tab_background #232834

color0  #232834
color8  #4a5263

color1  #b85c65
color9  #c86770

color2  #9db583
color10 #abc191

color3  #e5c17f
color11 #efcb89

color4  #7a96b7
color12 #89a4c5

color5  #ae86a3
color13 #bc92b1

color6  #83b6c8
color14 #91c4d6

color7  #dde2ec
color15 #e8ecf4
