lua << EOF
local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

--MACRO (reescrever escapes): normal $ybIs("imp_pa", { t("$a") }), 
ls.add_snippets("java", {
   s("imp_UrlBasedCorsConfigurationSource", { t("import org.springframework.web.cors.UrlBasedCorsConfigurationSource") }),
   s("imp_Claims", { t("import io.jsonwebtoken.Claims;") }), 
   s("imp_Jwts", { t("import io.jsonwebtoken.Jwts;") }), 
   s("imp_SignatureAlgorithm", { t("import io.jsonwebtoken.SignatureAlgorithm;") }), 
   s("imp_Decoders", { t("import io.jsonwebtoken.io.Decoders;") }), 
   s("imp_Keys", { t("import io.jsonwebtoken.security.Keys;") }), 
   s("imp_OpenAPIDefinition", { t("import io.swagger.v3.oas.annotations.OpenAPIDefinition;") }), 
   s("imp_SecuritySchemeIn", { t("import io.swagger.v3.oas.annotations.enums.SecuritySchemeIn;") }), 
   s("imp_SecuritySchemeType", { t("import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;") }), 
   s("imp_Contact", { t("import io.swagger.v3.oas.annotations.info.Contact;") }), 
   s("imp_Info", { t("import io.swagger.v3.oas.annotations.info.Info;") }), 
   s("imp_License", { t("import io.swagger.v3.oas.annotations.info.License;") }), 
   s("imp_SecurityRequirement", { t("import io.swagger.v3.oas.annotations.security.SecurityRequirement;") }), 
   s("imp_SecurityScheme", { t("import io.swagger.v3.oas.annotations.security.SecurityScheme;") }), 
   s("imp_Tag", { t("import io.swagger.v3.oas.annotations.tags.Tag;") }), 
   s("imp_Colum", { t("import jakarta.persistence.Column;") }), 
   s("imp_Entit", { t("import jakarta.persistence.Entity;") }), 
   s("imp_GeneratedValu", { t("import jakarta.persistence.GeneratedValue;") }), 
   s("imp_GenerationTyp", { t("import jakarta.persistence.GenerationType;") }), 
   s("imp_Id", { t("import jakarta.persistence.Id;") }), 
   s("imp_ManyToOn", { t("import jakarta.persistence.ManyToOne;") }), 
   s("imp_FilterChain", { t("import jakarta.servlet.FilterChain;") }), 
   s("imp_ServletException", { t("import jakarta.servlet.ServletException;") }), 
   s("imp_HttpServletRequest", { t("import jakarta.servlet.http.HttpServletRequest;") }), 
   s("imp_HttpServletResponse", { t("import jakarta.servlet.http.HttpServletResponse;") }), 
   s("imp_Valid", { t("import jakarta.validation.Valid;") }), 
   s("imp_NotBlank", { t("import jakarta.validation.constraints.NotBlank;") }), 
   s("imp_Size", { t("import jakarta.validation.constraints.Size;") }), 
   s("imp_Key", { t("import java.security.Key;") }), 
   s("imp_LocalDateTime", { t("import java.time.LocalDateTime;") }), 
   s("imp_Date", { t("import java.util.Date;") }), 
   s("imp_HashMap", { t("import java.util.HashMap;") }), 
   s("imp_List", { t("import java.util.List;") }), 
   s("imp_Map", { t("import java.util.Map;") }), 
   s("imp_Function", { t("import java.util.function.Function;") }), 
   s("imp_Collectors", { t("import java.util.stream.Collectors;") }), 
   s("imp_AllArgsConstructor", { t("import lombok.AllArgsConstructor;") }), 
   s("imp_Builder", { t("import lombok.Builder;") }), 
   s("imp_Data", { t("import lombok.Data;") }), 
   s("imp_Getter", { t("import lombok.Getter;") }), 
   s("imp_NoArgsConstructor", { t("import lombok.NoArgsConstructor;") }), 
   s("imp_RequiredArgsConstructor", { t("import lombok.RequiredArgsConstructor;") }), 
   s("imp_Setter", { t("import lombok.Setter;") }), 
   s("imp_ModelMapper", { t("import org.modelmapper.ModelMapper;") }), 
   s("imp_MatchingStrategies", { t("import org.modelmapper.convention.MatchingStrategies;") }), 
   s("imp_Bean", { t("import org.springframework.context.annotation.Bean;") }), 
   s("imp_Configuration", { t("import org.springframework.context.annotation.Configuration;") }), 
   s("imp_CreatedDate", { t("import org.springframework.data.annotation.CreatedDate;") }), 
   s("imp_JpaRepository", { t("import org.springframework.data.jpa.repository.JpaRepository;") }), 
   s("imp_HttpStatus", { t("import org.springframework.http.HttpStatus;") }), 
   s("imp_ResponseEntity", { t("import org.springframework.http.ResponseEntity;") }), 
   s("imp_PreAuthorize", { t("import org.springframework.security.access.prepost.PreAuthorize;") }), 
   s("imp_AuthenticationManager", { t("import org.springframework.security.authentication.AuthenticationManager;") }), 
   s("imp_AuthenticationProvider", { t("import org.springframework.security.authentication.AuthenticationProvider;") }), 
   s("imp_UsernamePasswordAuthenticationToken", { t("import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;") }), 
   s("imp_DaoAuthenticationProvider", { t("import org.springframework.security.authentication.dao.DaoAuthenticationProvider;") }), 
   s("imp_AuthenticationConfiguration", { t("import org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration;") }), 
   s("imp_EnableMethodSecurity", { t("import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;") }), 
   s("imp_HttpSecurity", { t("import org.springframework.security.config.annotation.web.builders.HttpSecurity;") }), 
   s("imp_EnableWebSecurity", { t("import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;") }), 
   s("imp_AbstractHttpConfigurer", { t("import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;") }), 
   s("imp_Authentication", { t("import org.springframework.security.core.Authentication;") }), 
   s("imp_AuthenticationException", { t("import org.springframework.security.core.AuthenticationException;") }), 
   s("imp_SecurityContextHolder", { t("import org.springframework.security.core.context.SecurityContextHolder;") }), 
   s("imp_UserDetails", { t("import org.springframework.security.core.userdetails.UserDetails;") }), 
   s("imp_UserDetailsService", { t("import org.springframework.security.core.userdetails.UserDetailsService;") }), 
   s("imp_UsernameNotFoundException", { t("import org.springframework.security.core.userdetails.UsernameNotFoundException;") }), 
   s("imp_BCryptPasswordEncoder", { t("import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;") }), 
   s("imp_PasswordEncoder", { t("import org.springframework.security.crypto.password.PasswordEncoder;") }), 
   s("imp_SecurityFilterChain", { t("import org.springframework.security.web.SecurityFilterChain;") }), 
   s("imp_UsernamePasswordAuthenticationFilter", { t("import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;") }), 
   s("imp_WebAuthenticationDetailsSource", { t("import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;") }), 
   s("imp_Component", { t("import org.springframework.stereotype.Component;") }), 
   s("imp_Repository", { t("import org.springframework.stereotype.Repository;") }), 
   s("imp_Service", { t("import org.springframework.stereotype.Service;") }), 
   s("imp_Transactional", { t("import org.springframework.transaction.annotation.Transactional;") }), 
   s("imp_CorsConfiguration", { t("import org.springframework.web.cors.CorsConfiguration;") }), 
   s("imp_CorsConfigurationSource", { t("import org.springframework.web.cors.CorsConfigurationSource;") }), 
   s("imp_UrlBasedCorsConfigurationSource", { t("import org.springframework.web.cors.UrlBasedCorsConfigurationSource;") }), 
   s("imp_OncePerRequestFilter", { t("import org.springframework.web.filter.OncePerRequestFilter;") }), 
})

EOF

