#!/bin/sh

BLANK='#00000000'  # Fundo transparente
CLEAR='#ffffff00'  # Fundo transparente
DEFAULT='#1e1d23'  # Cor de fundo do tema Catppuccin Mocha Teal
TEXT='#8dadf5'     # Cor de texto do tema Catppuccin Mocha Teal
WRONG='#ff6c6b'    # Cor de erro do tema Catppuccin Mocha Teal
VERIFYING='#3e8e41'  # Cor de verificação do tema Catppuccin Mocha Teal

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT         \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT          \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 9                     \
--clock                      \
--indicator                  \
--time-str="%H:%M"        \
--date-str="%A, %Y-%m-%d"       \
--keylayout 2                \

